services:
  lux-tts:
    image: ghcr.io/openttsgroup/lux-tts-open-tts:latest
    ports:
      - "8008:8000"
    volumes:
      - ./cache:/root/.cache
      - ../voices:/voices:ro
    environment:
      LUXTTS_MODEL: "YatharthS/LuxTTS"
      HF_ENDPOINT: "https://hf-mirror.com"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
